### ISSUE TITLE
error with fronius Primo

### ISSUE THREAD

**Issue by phsdv** [nielstron/pyfronius#2]
Running the example.py  (verison 0.2, with host address pointing to my inverter) gives error in _fetch_json()

```DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
  File "example.py", line 39, in <module>
    loop.run_until_complete(main(loop, host="192.168.1.11"))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "example.py", line 28, in main
    res = yield from fronius.current_system_inverter_data()
  File "/home/pi/computer/python/fronius/pyfronius/pyfronius/__init__.py", line 125, in current_system_inverter_data
    res = yield from self._fetch_json(URL_SYSTEM_INVERTER.format(self.protocol, self.host))
  File "/home/pi/computer/python/fronius/pyfronius/pyfronius/__init__.py", line 47, in _fetch_json
    return (yield from res.json())
  File "/home/pi/.local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 795, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/javascript'
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75f1e2f0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x768ec550>, 2185117.506892485)]']
connector: <aiohttp.connector.TCPConnector object at 0x75f1e310>
```

From the browser running the following url:
`http://192.168.1.11/solar_api/v1/GetInverterRealtimeData.cgi?Scope=System`
results in:
```
{
	"Head" : {
		"RequestArguments" : {
			"DataCollection" : "",
			"Scope" : "System"
		},
		"Status" : {
			"Code" : 0,
			"Reason" : "",
			"UserMessage" : ""
		},
		"Timestamp" : "2018-01-04T16:56:35+01:00"
	},
	"Body" : {
		"Data" : {
			"PAC" : {
				"Unit" : "W",
				"Values" : {
					"1" : 0
				}
			},
			"DAY_ENERGY" : {
				"Unit" : "Wh",
				"Values" : {
					"1" : 111
				}
			},
			"YEAR_ENERGY" : {
				"Unit" : "Wh",
				"Values" : {
					"1" : 2481
				}
			},
			"TOTAL_ENERGY" : {
				"Unit" : "Wh",
				"Values" : {
					"1" : 1817896
				}
			}
		}
	}
}
```
So network and inverter are running. No idea were the mimetype: text/javascript is coming from

**Comment by gbeine** [comment]
That comes from the inverter. It is responding with an irregular mime type to your request.
I had similar issues with my Symo inverters when they were offline.
What does happen if you use the device scope?

**Comment by phsdv** [comment]
the inverter is now off, I will try tomorrow again,

in my own version I used a bit different code that worked with out issues:
```
import aiohttp
import json
....
    async def fetch(self, session, url):
        with async_timeout.timeout(10):
            async with session.get(url) as response:
                return await response.text()

    async def getbaseurl(self):
        json_dict={}
        async with aiohttp.ClientSession() as session:
            r = await self.fetch(session, self.ip +  '/solar_api/GetAPIVersion.cgi')
            json_dict = json.loads(r)
            if 'APIVersion' in json_dict:
                self.apiversion = json_dict['APIVersion']
            if 'BaseURL' in json_dict:
                self.baseurl = json_dict['BaseURL']
                return True

    async def _isonline(self):
        try:
            apiversion = await self.getbaseurl()
            if apiversion:
                return True
        except aiohttp.client_exceptions.ClientConnectorError:
            self.apiversion = None
            self.baseurl = None
            return False

    async def DoRequest(self, url, params):
        online =  await self._isonline()
        if not online:
            if self.verbose:
                print("Not online?")
            return None
        async with aiohttp.ClientSession() as session:
            if self.baseurl:
                r = await self.fetch(session, self.ip + self.baseurl + url + "?" + urlencode(params))
                data = json.loads(r)
                self.errorcode = data["Head"]["Status"]["Code"]
                self.errortext = data["Head"]["Status"]["Reason"]
                if not "Body" in data.keys() or self.errorcode > 0:
                    if self.verbose:
                        print("ERROR: {} - {}".format(self.errorcode, self.errortext))
                    return False
                return data["Body"]
```
Main difference is that I use aiohttp get in fetch and then convert the text to json_dict. This works fine. 
To check if the inverter goes to sleep, when it is dark, I use exceptions. When the converter is off, you will get a connection error (aiohttp.client_exceptions.ClientConnectorError). In this case the code will return None. Not sure yet how to handle this properly in Home Assistent.

**Comment by gbeine** [comment]
I've just changed the way how the response is converted into JSON and commit it.
The problem is, that my implementation asks the server to send a application/json but the Fronius devices don't do this in random cases.
The fix does not insist on a specific mime type, which is exactly what your code does.
And what makes sense in this case :-)

**Comment by gbeine** [comment]
@phsdv please try the latest version from https://github.com/gbeine/pyfronius
If it works for you, I'll start an additional PR and you get the-first-bug-discovery-coffee :-)

**Comment by phsdv** [comment]
@gbeine not yet. I commented out a few lines in example as I only have 1 inverter (lines 18...25) and get an error:
```
~/computer/python/fronius/pyfronius $ python3 example.py 
DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
  File "example.py", line 39, in <module>
    loop.run_until_complete(main(loop, "192.168.1.11"))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "example.py", line 26, in main
    res = yield from fronius.current_inverter_data()
  File "/home/pi/computer/python/fronius/pyfronius/pyfronius/__init__.py", line 272, in current_inverter_data
    res = yield from self._fetch_json(URL_DEVICE_INVERTER_COMMON.format(self.protocol, self.host, device))
  File "/home/pi/computer/python/fronius/pyfronius/pyfronius/__init__.py", line 46, in _fetch_json
    return json.load(res)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'generator'
```

**Comment by gbeine** [comment]
@phsdv There may be a difference between Python 3.5 and 3.6
I have only 3.6 running for both, development environment and HA.

**Comment by phsdv** [comment]
@gbeine as Home Assistant supports minimal python 3.4.2 we should get this working on 3.4 and 3.5 as well.

I tried what was mentioned in the answer here: [stackoverflow.com async-with-in-python-3-4](https://stackoverflow.com/questions/37465816/async-with-in-python-3-4) And got some promising results until to son went down. So I could not test it very well.
```
    @asyncio.coroutine
    def _fetch_json(self, url):
        with async_timeout.timeout(10):
            res = yield from self._aio_session.get(url)
            return (yield from res.text())
```
and each call should have a json.loads afterward like this: (I was not able yet to get the json_load(s?) working in the fetch co-routine)
```
        r = yield from self._fetch_json(URL_SYSTEM_INVERTER.format(self.protocol, self.host))
        res = json.loads(r)
        _LOGGER.debug(res)

```
I assume we should use json.loads() and json.load() as we do not read a file but a string (or similar).

Some partial result:
```
~/computer/python/fronius/pyfronius $ python3 example.py 
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:pyfronius:{
	"Head" : {
		"RequestArguments" : {
			"DataCollection" : "CommonInverterData",
			"DeviceClass" : "Inverter",
			"DeviceId" : "1",
			"Scope" : "Device"
		},
...
```

**Comment by phsdv** [comment]
@gbeine the following code for _fetch_json() works for me:
```    @asyncio.coroutine
    def _fetch_json(self, url):
        with async_timeout.timeout(10):
            res = yield from self._aio_session.get(url)
            text = yield from res.text()
            return json.loads(text)
```
This returns a json dictionary so no other changes are needed.

**Comment by gbeine** [comment]
@phsdv Great, I'll merge and test it.
