### ISSUE TITLE
time out exception

### ISSUE THREAD

**Issue by phsdv** [nielstron/pyfronius#5]
Not sure how to handle this one, but when the inverter shutdown for the night, an TimeoutError exception will be trown:
```
Traceback (most recent call last):
  File "example.py", line 55, in <module>
    loop.run_until_complete(main(loop, "192.168.1.11"))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "example.py", line 19, in main
    res = yield from fronius.current_power_flow()
  File "/home/pi/computer/python/fronius/pyfronius/pyfronius/__init__.py", line 54, in current_power_flow
    res = yield from self._fetch_json(URL_POWER_FLOW.format(self.protocol, self.host))
  File "/home/pi/computer/python/fronius/pyfronius/pyfronius/__init__.py", line 47, in _fetch_json
    return json.loads(text)
  File "/home/pi/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 35, in __exit__
    self._do_exit(exc_type)
  File "/home/pi/.local/lib/python3.5/site-packages/async_timeout/__init__.py", line 80, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75e4f0b0>
```
The reason I wanted to write my own pyfronius module is to handle these conditions nicely and we do not get a lot of errors in the HA log file. For me it would be perfect if HA would know the inverter is sleeping and we can see that in the status in HA as well.

**Comment by gbeine** [comment]
This happens not only if the inverter is sleeping.
The timeout occurs on all my Fronius devices if the polling rate is too high and timeout is too low.

You cannot get the information that the inverter is sleeping from this exception.
That's why it makes sense to throw it through to the caller.

I handle this exception within HA as well as the ServerDisconnectedError.
As HA is responsible for the polling rate to the device, it should know about this exception.

Have a look here:
https://github.com/gbeine/home-assistant/blob/fronius/homeassistant/components/sensor/fronius.py#L120
No errors for the HA log if you don't want them.

**Comment by gbeine** [comment]
The timeout for HTTP can now be set from outside:
https://github.com/nielstron/pyfronius/blob/master/pyfronius/__init__.py#L32

Beware too high polling rate, the Fronius devices are only of limited capacity.

Nevertheless, I think that exceptions should be thrown out of the library.
